controller_manager:
  ros__parameters:
    update_rate: 50  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    four_wheel_steering_controller:
      type: four_wheel_steering_controller/FourWheelSteeringController
    
four_wheel_steering_controller:
  ros__parameters:
    front_left_wheel: fl_wheel
    front_right_wheel: fr_wheel
    rear_left_wheel: rl_wheel
    rear_right_wheel: rr_wheel
    front_left_steering: fl_steering_wheel
    front_right_steering: fr_steering_wheel
    rear_left_steering: rl_steering_wheel
    rear_right_steering: rr_steering_wheel
	
    track: 0.423065
    wheel_radius: 0.1
    wheel_base: 0.490102
    wheel_steering_y_offset: 0.0316228
    
    publish_rate: 50.0
    open_loop: true
    enable_odom_tf: true
    cmd_vel_timeout: 1.0
    odom_frame_id: odom
    base_frame_id: base_footprint
	wait_for_angle: true
	min_steering_diff: 0.05
    
    # Velocity and acceleration limits
    # Whenever a min_* is unspecified, default to -max_*
    linear:
      x:
        has_velocity_limits    : true
        max_velocity           : 1.667  # m/s
        min_velocity           : -1.667 # m/s
        has_acceleration_limits: true
        max_acceleration       : 1.0  # m/s^2
        min_acceleration       : -1.0 # m/s^2
    angular:
      z:
        has_velocity_limits    : true
        max_velocity           : 3.14  # rad/s
        min_velocity           : -3.14
        has_acceleration_limits: true
        max_acceleration       : 1.0  # rad/s^2
        min_acceleration       : -1.0
